### ISSUE TITLE
Needs a /cancel or /quit command

### ISSUE THREAD

**Issue by edisonchee** [edisonchee/butler-bot#3]
@yuhong90 
Should we introduce a command to cancel the interaction flow? This is similar to BotFather's /cancel command.

**Comment by yuhong90** [comment]
yes we should. Need a good way to exit the interaction at any step.

**Comment by yuhong90** [comment]
@edisonchee should the booking interaction timeout if you take too long to complete? might solve the problem of multiple opened interactions within the chat. Thoughts?

**Comment by edisonchee** [comment]
@yuhong90 yes good idea too. the timeout function should edit messages of open interactions to close them for consistent UX.

or we could prevent multiple open interactions by closing all when a new booking command is issued.

does this mean we'll need to store message.ids somewhere?
